### ISSUE TITLE
Bump to latest Owasp DependencyCheck

### ISSUE THREAD

**Issue by AlexanderMann** [rm-hull/lein-nvd#14]
# Motivation
Errors such as: 
```
[2017-11-14 16:25:50.124] ERROR CentralAnalyzer - Could not connect to Central search. Analysis failed.
java.io.IOException: Finally failed connecting to Central search. Giving up after 5 tries.
	at org.owasp.dependencycheck.analyzer.CentralAnalyzer.fetchMavenArtifacts(CentralAnalyzer.java:288)
	at org.owasp.dependencycheck.analyzer.CentralAnalyzer.analyzeDependency(CentralAnalyzer.java:198)
	at org.owasp.dependencycheck.analyzer.AbstractAnalyzer.analyze(AbstractAnalyzer.java:137)
	at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:88)
	at org.owasp.dependencycheck.AnalysisTask.call(AnalysisTask.java:37)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Could not connect to MavenCentral (400): Bad Request
	at org.owasp.dependencycheck.data.central.CentralSearch.searchSha1(CentralSearch.java:181)
	at org.owasp.dependencycheck.analyzer.CentralAnalyzer.fetchMavenArtifacts(CentralAnalyzer.java:266)
	... 8 more
```

https://github.com/jeremylong/DependencyCheck/tree/v3.0.2
https://github.com/jeremylong/DependencyCheck/issues/978

# Suggested Musical Pairing
https://soundcloud.com/wax-poetics/instant-classic-selection

**Comment by AlexanderMann** [comment]
Trying something like didn't work:

```
            [lein-nvd "0.4.0"]
            [nvd-clojure "0.4.0"
             :exclusions [org.owasp/dependency-check-core]]
            ;; Remove when lein-nvd uses latest dependency-check-core
            [org.owasp/dependency-check-core "3.0.2"]
```

**Comment by rm-hull** [comment]
Version 0.4.1 released to clojars 🚀
