### ISSUE TITLE
Cant run the example project - java.lang.NoSuchMethodError 

### ISSUE THREAD

**Issue by ChadHarrisVerr** [rm-hull/lein-nvd#26]
I am receiving the following exception running the included example project. on master commit 58cfea4f8044eae09ca465d334885afdc2f8a73a using lein 2.7.1. Anyone seen this before ?

When running the Exception in thread "main" java.lang.NoSuchMethodError: org.apache.commons.io.IOUtils.toString(Ljava/io/InputStream;Ljava/nio/charset/Charset;)Ljava/lang/String;, compiling:(/private/var/folders/32/k631300x10xgjqf3gpxgc38r0000gn/T/form-init2800230060992263135.clj:1:125)
        at clojure.lang.Compiler.load(Compiler.java:7526)
        at clojure.lang.Compiler.loadFile(Compiler.java:7452)
        at clojure.main$load_script.invokeStatic(main.clj:278)
        at clojure.main$init_opt.invokeStatic(main.clj:280)
        at clojure.main$init_opt.invoke(main.clj:280)
        at clojure.main$initialize.invokeStatic(main.clj:311)
        at clojure.main$null_opt.invokeStatic(main.clj:345)
        at clojure.main$null_opt.invoke(main.clj:342)
        at clojure.main$main.invokeStatic(main.clj:424)
        at clojure.main$main.doInvoke(main.clj:387)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.lang.Var.applyTo(Var.java:702)
        at clojure.main.main(main.java:37)

**Comment by ChadHarrisVerr** [comment]
Actually just upgraded lein to 2.8.1 and resolved this....
