### ISSUE TITLE
ExceptionCollection error

### ISSUE THREAD

**Issue by krestivo-kdinfotech** [rm-hull/lein-nvd#33]
```
[2019-04-25 10:47:13.180] INFO Engine - Finished CPE Analyzer (0 seconds)
[2019-04-25 10:47:13.181] INFO Engine - Finished False Positive Analyzer (0 seconds)
[2019-04-25 10:47:13.184] INFO Engine - Finished NVD CVE Analyzer (0 seconds)
[2019-04-25 10:47:13.207] INFO Engine - Finished Vulnerability Suppression Analyzer (0 seconds)
[2019-04-25 10:47:13.213] INFO Engine - Finished Dependency Bundling Analyzer (0 seconds)
[2019-04-25 10:47:13.247] INFO Engine - Analysis Complete (1 seconds)
Exception in thread "main" Syntax error compiling at (/tmp/form-init12567659599026164559.clj:1:74).
	at clojure.lang.Compiler.load(Compiler.java:7647)
	at clojure.lang.Compiler.loadFile(Compiler.java:7573)
	at clojure.main$load_script.invokeStatic(main.clj:452)
	at clojure.main$init_opt.invokeStatic(main.clj:454)
	at clojure.main$init_opt.invoke(main.clj:454)
	at clojure.main$initialize.invokeStatic(main.clj:485)
	at clojure.main$null_opt.invokeStatic(main.clj:519)
	at clojure.main$null_opt.invoke(main.clj:516)
	at clojure.main$main.invokeStatic(main.clj:598)
	at clojure.main$main.doInvoke(main.clj:561)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:705)
	at clojure.main.main(main.java:37)
Caused by: org.owasp.dependencycheck.exception.ExceptionCollection: One or more exceptions occurred during dependency-check analysis
	The download was interrupted; unable to complete the update
	at org.owasp.dependencycheck.Engine.analyzeDependencies(Engine.java:693)
	at nvd.task.check$scan_and_analyze.invokeStatic(check.clj:43)
	at nvd.task.check$scan_and_analyze.invoke(check.clj:38)
	at nvd.task.check$_main.invokeStatic(check.clj:54)
	at nvd.task.check$_main.invoke(check.clj:51)
	at user$eval678.invokeStatic(form-init12567659599026164559.clj:1)
	at user$eval678.invoke(form-init12567659599026164559.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:7176)
	at clojure.lang.Compiler.eval(Compiler.java:7166)
	at clojure.lang.Compiler.load(Compiler.java:7635)
	... 12 more
Subprocess failed
```

running 1.0.0

**Comment by rm-hull** [comment]
Sounds like the download failed halfway through. Try `lein nvd purge` and then `lein nvd check`

**Comment by krestivo-kdinfotech** [comment]
It seems impossible to get this to succeed on the first try. Would it be possible to add retry logic so that the entire task doesn't fail if one or more of the files doesn't download on the first attempt?

**Comment by rm-hull** [comment]
Lein nvd is just a very thin wrapper around a java library called dependency-check. You would need to appeal to the author of that library to add that logic (or maybe dig into its documentation to see if it already exists).

I haven’t ever experienced this specific problem. Can you provide a bit more information as to the OS you are using, what JVM version, etc, as well as approx geographic location, internet connection type (cable, ADSL, 4G) and rated download speed.

**Comment by krestivo-kdinfotech** [comment]
I'll do that, thanks.

It's a persistent problem. Takes about 4-5 tries to get lein nvd to complete.

This is on Linux Debian Buster, Menlo Park, on a 1Gbps Comcast fiber business connection. fast.com says 780Mbps down, 1Gbps up. DNS is bind9 local caching. Hardware is a ThinkPad Yoga.

JVM is 

```
openjdk version "11.0.3" 2019-04-16
OpenJDK Runtime Environment (build 11.0.3+1-Debian-1)
OpenJDK 64-Bit Server VM (build 11.0.3+1-Debian-1, mixed mode, sharing)
```

**Comment by rm-hull** [comment]
Related: https://github.com/jeremylong/DependencyCheck/issues/1558

**Comment by mtravers** [comment]
Running into the same problem, running on a Mac, with JVM
```
java version "1.8.0_191"
Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.191-b12, mixed mode)
```

Purge and recheck doesn't seem to fix it. Don't know the specifics of my net connection but it's pretty good, we deal with large file transfers all the time.

The syntax error is from reading a tmp .clj file whose entire content is:
```
(ns )
```
Not sure where this comes from, but it seems unlikely to be caused by a Java library.

**Comment by rm-hull** [comment]
>Not sure where this comes from, but it seems unlikely to be caused by a Java library.

Lein-nvd uses dependency-check to do the actual work, and reading through the discourse in the issue mentioned above, I think we have to sit tight until dependency-check 5.0.0 is released -- at which point we can upgrade to that version, and hopefully this regression will be resolved.

Obviously the other way we could go is to use an earlier version of dependency-check that didn't suffer this problem.

**Comment by wegeliuz** [comment]
dependency-check 5.0.0 is now released: https://github.com/jeremylong/DependencyCheck/releases/tag/v5.0.0

**Comment by rm-hull** [comment]
lein-nvd 1.1.0 released with dependency-check 5

**Comment by krestivo-kdinfotech** [comment]
Thanks!

**Comment by bostonaholic** [comment]
I'm still having problems even after upgrading to 1.1.0 (and 1.1.1). `purge` and `check` aren't fixing it, either. I have also deleted the data directory manually.

```
