### ISSUE TITLE
NullPointerException when running lein nvd check on 1.1.0

### ISSUE THREAD

**Issue by putsi** [rm-hull/lein-nvd#37]
Hi,

I'm getting the below exception when running against the example project (or against any project):

```
[2019-06-14 23:46:54.326] INFO AbstractDiskCache - In dispose, destroying event queue.
[2019-06-14 23:46:54.327] INFO IndexedDiskCache - Region [CENTRAL] Saving keys to: CENTRAL, key count: 0
[2019-06-14 23:46:54.327] INFO IndexedDiskCache - Region [CENTRAL] Finished saving keys.
[2019-06-14 23:46:54.327] INFO IndexedDiskCache - Region [CENTRAL] Shutdown complete.
[2019-06-14 23:46:54.327] INFO CompositeCache - In DISPOSE, [CENTRAL] disposing of memory cache.
[2019-06-14 23:46:54.327] INFO AbstractMemoryCache - Memory Cache dispose called.
Exception in thread "main" java.lang.NullPointerException, compiling:(/tmp/form-init8052204418056509289.clj:1:73)
	at clojure.lang.Compiler.load(Compiler.java:7526)
	at clojure.lang.Compiler.loadFile(Compiler.java:7452)
	at clojure.main$load_script.invokeStatic(main.clj:278)
	at clojure.main$init_opt.invokeStatic(main.clj:280)
	at clojure.main$init_opt.invoke(main.clj:280)
	at clojure.main$initialize.invokeStatic(main.clj:311)
	at clojure.main$null_opt.invokeStatic(main.clj:345)
	at clojure.main$null_opt.invoke(main.clj:342)
	at clojure.main$main.invokeStatic(main.clj:424)
	at clojure.main$main.doInvoke(main.clj:387)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:702)
	at clojure.main.main(main.java:37)
Caused by: java.lang.NullPointerException
	at nvd.report$score.invokeStatic(report.clj:52)
	at nvd.report$score.invoke(report.clj:51)
	at nvd.report$vuln_status$iter__609__613$fn__614$fn__615.invoke(report.clj:72)
	at nvd.report$vuln_status$iter__609__613$fn__614.invoke(report.clj:71)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.Cons.next(Cons.java:39)
	at clojure.lang.LazySeq.next(LazySeq.java:81)
	at clojure.lang.RT.next(RT.java:706)
	at clojure.core$next__5108.invokeStatic(core.clj:64)
	at clojure.string$join.invokeStatic(string.clj:180)
	at clojure.string$join.invoke(string.clj:180)
	at nvd.report$vuln_status.invokeStatic(report.clj:70)
	at nvd.report$vuln_status.invoke(report.clj:67)
	at nvd.report$vulnerabilities$iter__624__628$fn__629.invoke(report.clj:79)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.Cons.next(Cons.java:39)
	at clojure.lang.RT.length(RT.java:1777)
	at clojure.lang.RT.seqToArray(RT.java:1718)
	at clojure.lang.LazySeq.toArray(LazySeq.java:130)
	at clojure.lang.RT.toArray(RT.java:1691)
	at clojure.core$to_array.invokeStatic(core.clj:344)
	at clojure.core$sort.invokeStatic(core.clj:3105)
	at clojure.core$sort_by.invokeStatic(core.clj:3111)
	at clojure.core$sort_by.invokeStatic(core.clj:3111)
	at clojure.core$sort_by.invoke(core.clj:3111)
	at nvd.report$vulnerabilities.invokeStatic(report.clj:76)
	at nvd.report$vulnerabilities.invoke(report.clj:75)
	at nvd.report$print_summary.invokeStatic(report.clj:89)
	at nvd.report$print_summary.invoke(report.clj:86)
	at nvd.task.check$_main.invokeStatic(check.clj:54)
	at nvd.task.check$_main.invoke(check.clj:51)
	at user$eval688.invokeStatic(form-init8052204418056509289.clj:1)
	at user$eval688.invoke(form-init8052204418056509289.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:7062)
	at clojure.lang.Compiler.eval(Compiler.java:7052)
	at clojure.lang.Compiler.load(Compiler.java:7514)
	... 12 more
```

```
# java -version
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-8u212-b03-0ubuntu1.19.04.2-b03)
OpenJDK 64-Bit Server VM (build 25.212-b03, mixed mode)

# lein -version
Leiningen 2.9.1 on Java 1.8.0_212 OpenJDK 64-Bit Server VM
```

Any ideas how to solve this?

**Comment by putsi** [comment]
Tested with master and running `lein test` completes tests just fine but running `lein nvd check` on `examples/` results in the same exception.

**Comment by rm-hull** [comment]
Will push out 1.1.1 shortly...

**Comment by putsi** [comment]
Hey @rm-hull,

Can confirm that it works now with b719f26.

Thanks for the fast fix!
